version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      # - ./src/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - "./mongo/db:/data/db"
    # env_file:
    #   - ./src/config/.env
    ports:
      - "27017:27017"
  #    environment:
  #      MONGO_INITDB_DATABASE: db
  #      MONGO_INITDB_ROOT_USERNAME: adeola17
  #      MONGO_INITDB_ROOT_PASSWORD: Adevictor17

  rabbitmq:
    image: rabbitmq
    container_name: "rabbit"
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #    networks:
  #      - rabbitmq_nodejs

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./user-service/:/src
      - /src/node_modules
    env_file:
      - ./user-service/.env
    environment:
      MONGO_ADDRESS: mongodb
    ports:
      - 1200:1200
    depends_on:
      - mongodb

  product-service:
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./product-service/:/src
      - /src/node_modules
    env_file:
      - ./product-service/.env
    environment:
      MONGO_ADDRESS: mongodb
    ports:
      - 1201:1201
    depends_on:
      - mongodb

  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./order-service/:/src
      - /src/node_modules
    env_file:
      - ./order-service/.env
    environment:
      MONGO_ADDRESS: mongodb
    ports:
      - 1202:1202
    depends_on:
      - mongodb

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./payment-service/:/src
      - /src/node_modules
    env_file:
      - ./payment-service/.env
    environment:
      MONGO_ADDRESS: mongodb
    ports:
      - 1203:1203
    depends_on:
      - mongodb
      - rabbitmq

  #  volumes:
  #    db-data:
  #      driver: local
#  networks:
#    rabbitmq_nodejs:
#      driver: bridge
